language: nix
script: "./travis/build.sh"
after_success: "./travis/trigger-downstream.sh"
cache:
  timeout: 86400
  directories:
  - "${HOME}/.m2"
branches:
  only:
  - master
env:
  global:
  - AWS_DEFAULT_REGION: ap-southeast-2
  # TRAVIS_TOKEN
  - secure: Y7BAj6oYGbLU5jNswZrWLH5m5tPuitlsbKgW6luZ2FKBKTnkl77p0hyb+KHbg3Gzg7meQ971SKhnd5UgGecaz6Ych40GW16/gYPEUDxMIs12/bODYTlsdE3wgHk2IzjAa4SShO20kJgeFi4jhUzxSNo6oYV0o+EHMmtT2oHaEMA=
  - AWS_ACCESS_KEY_ID: AKIAJBSOFDJSDGWCKQ3Q
  # AWS_SECRET_ACCESS_KEY, /geodesy-operations/iam-user/geodesy-operations-pipelines-dev/access-key/AKIAJBSOFDJSDGWCKQ3Q/secret-access-key
  - secure: PFmRrND5Ss4YsCRdUVKXKPD/jver1ACnU5eedNbtfIjIjyBOLi/rHKnvU6tJNvHEPZLKFxOzVbGt8gEJmWHMYIsKh1uLLjn86u6dm2JnIo5KeU9Vdjx+XS3yJv4LAj+rNEfQ7mXSQJk0qw7sc3kyQhPQISZWRxn6Wg4yeZo51uA=
