language: nix
script: "./travis/build.sh"
after_success: "./travis/trigger-downstream.sh"
cache:
  timeout: 86400
  directories:
  - "${HOME}/.m2"
branches:
  only:
  - master
env:
  global:
  - AWS_DEFAULT_REGION: ap-southeast-2
  # TRAVIS_TOKEN
  - secure: Y7BAj6oYGbLU5jNswZrWLH5m5tPuitlsbKgW6luZ2FKBKTnkl77p0hyb+KHbg3Gzg7meQ971SKhnd5UgGecaz6Ych40GW16/gYPEUDxMIs12/bODYTlsdE3wgHk2IzjAa4SShO20kJgeFi4jhUzxSNo6oYV0o+EHMmtT2oHaEMA=
  - AWS_ACCESS_KEY_ID: AKIA2AV2YTL6SUSQP56W
  # AWS_SECRET_ACCESS_KEY, /geodesy-operations/iam-user/travis-ci/access-key/AKIA2AV2YTL6SUSQP56W/secret-access-key
  - secure: EV7W3lWDVU/KTvXYduNuXLk/ksDGORdotRQ7eyRVOnT2+G2mK07peJrIO9nE3A93JmlzmzRFrMJ4ckavK6LXCuca61opmjJwO6bVoZYEScxCqRkI+nHOOpbvjKWF6Q66NXYSzMJCF0oJIzwJZSI8icpyVhbYd32NfK8l4xaQhLQ=
