language: nix
script: "./travis/build.sh"
after_success: "./travis/trigger-downstream.sh"
cache:
  timeout: 86400
  directories:
  - "${HOME}/.m2"
branches:
  only:
  - master
  - next
env:
  global:
  - secure: QRuP8ERANjKtFKR2KX8/v3QgHn8plc6ICeyY4pNYk4OnZeDRH/1tP6CQRau2+FoJRmS+u62VRK0Wv8Zdt1QaCgLs3MoaQhAhLQk9HcH4rATL0xsoCFrkZM8sURkWTwQqR9XlP2M0aVWLCd6bxb0hdwXk96Q14+4l/gBw9lfJMQY=
  - secure: HRWoQjw/DkSPZU5q4Clq3Uk5qffoRYLPbVuV7IdXpBuJOcF3PZV3j5Nydq55aPAu8befkS+bxj3XJA46mFAf/4WKI4xtyA/rVz6KLupZAHdSOkyvx4YNgyOE9YnTEbvNKSNvg+WMFXTfZIX/miKe1mbq/pCnSNU6S92xJpPXLBA=
  - secure: Y7BAj6oYGbLU5jNswZrWLH5m5tPuitlsbKgW6luZ2FKBKTnkl77p0hyb+KHbg3Gzg7meQ971SKhnd5UgGecaz6Ych40GW16/gYPEUDxMIs12/bODYTlsdE3wgHk2IzjAa4SShO20kJgeFi4jhUzxSNo6oYV0o+EHMmtT2oHaEMA=
